---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ml-inference-monitor
  namespace: ml-inference  
  labels:
    app: ml-inference
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: ml-inference  
  endpoints:
  - port: http           
    path: /health       
    interval: 30s        
    scrapeTimeout: 10s  
    